import uniqid from "uniqid";

const List = [
    {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-bl.webp"),
    name: "Gallo Sunglasses",
    id: '123451',
    price: 250,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-blk.webp"),
    name: "Gallo Sunglasses",
    id: '123452',
    price: 250,
    description: [
      "Black acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-br.webp"),
    name: "Gallo Sunglasses",
    id: '123453',
    price: 250,
    description: [
      "Light tortoiseshell acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  // {
  //   itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-fire.webp"),
  //   name: "Gallo Sunglasses",
  //   id: uniqid(),
  //   price: 250,
  //   description: [
  //     "Tortoiseshell acetate sunglasses",
  //     "Non-polarized lenses",
  //     "Blue acetate sunglasses",
  //     "Non-polarized lenses",
  //     "Gold foil logo at interior temple",
  //     "Five barrel hinges",
  //     "Comes in branded box with leather case",
  //     "100% Acetate",
  //     "Wipe clean",
  //     "Made in Japan",
  //   ],
  // },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-wh.webp"),
    name: "Gallo Sunglasses",
    id: '123454',
    price: 250,
    description: [
      "Clear acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirt-bl.webp"),
    name: "ALD Uniform Tee",
    id: '123455',
    price: 85,
    description: [
      "Navy tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirt-go.webp"),
    name: "ALD Uniform Tee",
    id: '123456',
    price: 85,
    description: [
      "Tan tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirt-gr.webp"),
    name: "ALD Uniform Tee",
    id: '123457',
    price: 85,
    description: [
      "Green tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirt-gry.webp"),
    name: "ALD Uniform Tee",
    id: uniqid(),
    price: 85,
    description: [
      "Gray tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirt-wh.webp"),
    name: "ALD Uniform Tee",
    id: '123458',
    price: 85,
    description: [
      "White tee",
      "12oz Jersey fabric",
      "Embroidered logo at center front",
      "Ribbed neck",
      "Featured branded loop label",
      "100% Cotton",
      "Machine wash",
      "Made in Canada",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shorts-bl.webp"),
    name: "Logo Gym Short",
    id: '123459',
    price: 95,
    description: [
      "Blue swim shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shorts-blk.webp"),
    name: "Logo Gym Short",
    id: '223451',
    price: 95,
    description: [
      "Black swim shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirt-wh.webp"),
    name: "Logo Gym Short",
    id: '223452',
    price: 95,
    description: [
      "White swim shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shorts-gr.webp"),
    name: "Logo Gym Short",
    id: '223453',
    price: 95,
    description: [
      "Green swim shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shorts-ye.webp"),
    name: "Logo Gym Short",
    id: '223454',
    description: [
      "Yellow Gym shorts",
      "Embroidered logo at left leg",
      "Mesh lined",
      "Elasticized waistband with flat braided drawstrings",
      "Two on-seam pockets at front",
      "One patch pocket at back",
      "100% Polyester",
      "Machine wash",
      "Made in China",
    ],
    price: 95,
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirt-brown.jpg"),
    name: "RROUND Reworked TCD",
    id: '22345',
    price: 49,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirt.jpg"),
    name: "RROUND Logo",
    id: '223456',
    price: 49,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shorts-rr1.jpg"),
    name: "RROUND Logo Shorts",
    id: '223457',
    price: 65,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shorts-rr.jpg"),
    name: "RROUND Logo Shorts",
    id: '223458',
    price: 65,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirts-gray.jpg"),
    name: "RROUND Reworked TCD",
    id: '223459',
    price: 49,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/hoodie.jpg"),
    name: "RROUND Logo Sweater",
    id: '323451',
    price: 250,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/shirt-logo.jpg"),
    name: "RROUND Logo",
    id: '323452',
    price: 49,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
]

export default List;

