import uniqid from "uniqid";

const List = [
    {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-bl.webp"),
    name: "Gallo Sunglasses",
    id: uniqid(),
    price: 250,
    description: [
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-blk.webp"),
    name: "Gallo Sunglasses",
    id: uniqid(),
    price: 250,
    description: [
      "Black acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-br.webp"),
    name: "Gallo Sunglasses",
    id: uniqid(),
    price: 250,
    description: [
      "Light tortoiseshell acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
  // {
  //   itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-fire.webp"),
  //   name: "Gallo Sunglasses",
  //   id: uniqid(),
  //   price: 250,
  //   description: [
  //     "Tortoiseshell acetate sunglasses",
  //     "Non-polarized lenses",
  //     "Blue acetate sunglasses",
  //     "Non-polarized lenses",
  //     "Gold foil logo at interior temple",
  //     "Five barrel hinges",
  //     "Comes in branded box with leather case",
  //     "100% Acetate",
  //     "Wipe clean",
  //     "Made in Japan",
  //   ],
  // },
  {
    itemImage: require("/Users/kjocampo/Desktop/shopping-react/react-shopping/src/item-images/glasses-wh.webp"),
    name: "Gallo Sunglasses",
    id: uniqid(),
    price: 250,
    description: [
      "Clear acetate sunglasses",
      "Non-polarized lenses",
      "Blue acetate sunglasses",
      "Non-polarized lenses",
      "Gold foil logo at interior temple",
      "Five barrel hinges",
      "Comes in branded box with leather case",
      "100% Acetate",
      "Wipe clean",
      "Made in Japan",
    ],
  },
]

export default List;

